version: '1'

networks:
  net-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - net-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-broker-1:
    image: 'bitnami/kafka:latest'
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
    networks:
      - net-tier
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - './kafka/kafka-persistence-broker-1:/bitnami/kafka'
    depends_on:
      - zookeeper
  kafka-broker-2:
    image: 'bitnami/kafka:latest'
    container_name: kafka-broker-2
    ports:
      - "9093:9093"
    networks:
      - net-tier
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://127.0.0.1:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - './kafka/kafka-persistence-broker-2:/bitnami/kafka'
    depends_on:
      - zookeeper
  kafka-broker-3:
    image: 'bitnami/kafka:latest'
    container_name: kafka-broker-3
    ports:
      - "9094:9094"
    networks:
      - net-tier
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://127.0.0.1:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - './kafka/kafka-persistence-broker-3:/bitnami/kafka'
    depends_on:
      - zookeeper
