spring:
  profiles:
    active:
    - local
server:
  port: 8082    
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    template:
      default-topic: badge-topic-javas
    producer:
      bootstrap-servers: locahost:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap-servers: locahost:29092
        